[theme]
primaryColor = '#1f77b4'
backgroundColor = '#0e1117'
secondaryBackgroundColor = '#ffffff'  # This changes the sidebar background to white
textColor = '#000000'  # Adjust text color for readability
font = "sans serif"
